###
POST http://localhost:8080/Spring01hibernate/book/create?title=potop&rating=8&description=dobre

###
POST http://localhost:8080/Spring01hibernate/book/edit/1?title=esited&rating=5&description=super

###

GET http://localhost:8080/Spring01hibernate/book/all
###

POST http://localhost:8080/Spring01hibernate/author/create?firstName=Adam&lastName=Nowak
###
POST http://localhost:8080/Spring01hibernate/author/create?firstName=Kasia&lastName=Kowalska
###
GET http://localhost:8080/Spring01hibernate/author/all
###
GET http://localhost:8080/Spring01hibernate/author/find/2
###
POST http://localhost:8080/Spring01hibernate/author/delete/1
###
POST http://localhost:8080/Spring01hibernate/publisher/create?name=Warsaw2025
###
GET http://localhost:8080/Spring01hibernate/publisher/all
###
POST http://localhost:8080/Spring01hibernate/publisher/edit/1?name=Warsaw2023
###
POST http://localhost:8080/Spring01hibernate/publisher/delete/3
###